### ISSUE TITLE
SSR error: Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by matheusdavidson** [MurhafSousli/ngx-gallery#138]
#### What is the expected behavior?
Work with SSR

#### What is the current behavior?
When i start the server via SSR i get this error:
```bash
TypeError: Cannot read property 'complete' of undefined
    at GallerizeDirective.ngOnDestroy (/private/var/www/superrofertas/site/dist/server.js:197715:33)
    at callProviderLifecycles (/private/var/www/superrofertas/site/dist/server.js:13226:18)
    at callElementProvidersLifecycles (/private/var/www/superrofertas/site/dist/server.js:13194:13)
    at callLifecycleHooksChildrenFirst (/private/var/www/superrofertas/site/dist/server.js:13184:29)
    at destroyView (/private/var/www/superrofertas/site/dist/server.js:14246:5)
    at callViewAction (/private/var/www/superrofertas/site/dist/server.js:14372:13)
    at execComponentViewsAction (/private/var/www/superrofertas/site/dist/server.js:14294:13)
    at destroyView (/private/var/www/superrofertas/site/dist/server.js:14245:5)
    at callViewAction (/private/var/www/superrofertas/site/dist/server.js:14372:13)
    at execComponentViewsAction (/private/var/www/superrofertas/site/dist/server.js:14294:13)
```

#### What are the steps to reproduce?
Get universal starter project and use gallerize directive

#### Which versions are you using for the following packages?

Angular: 6.0.7
Angular CDK: 6.3.3
Angular CLI: 6.0.8
Typescript: 2.7.2
Gallery: ^3.0.2

**Comment by matheusdavidson** [comment]
Sorry for the noob question but how can i install this from master? Tried as usual but couldn't get it to work.

**Comment by MurhafSousli** [comment]
@matheusdavidson Try `npm i git+https://git@github.com/MurhafSousli/ngx-gallery.git`

And just import the **GallerizeModule** from there

```ts
import { GallerizeModule } from 'ngx-gallery/projects/gallerize/src/lib/public_api'
```

Please test it and let me know if it fixes the issue with Universal.

**Comment by MurhafSousli** [comment]
@matheusdavidson I haven't tested it, if the fix worked let me know so I can publish a new version :)

**Comment by matheusdavidson** [comment]
Hi, thank you for your feedback, i will try it out today and will get back to you.
