### ISSUE TITLE
WARNING in ngx-gallery-core.js - export 'inject' was not found in '@angular/core' at HarmonyImportSpecifierDependency._getErrors

### ISSUE THREAD

**Issue by ben4d85** [MurhafSousli/ngx-gallery#147]
#### What is the expected behavior?

Gallery should work out of the box without warnings.

#### What is the current behavior?

After installing the gallery following the wiki , I receive the following warning:

```
WARNING in ./node_modules/@ngx-gallery/core/fesm5/ngx-gallery-core.js
573:125-131 "export 'inject' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\Ben\node\mytest\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\Ben\node\mytest\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\Ben\node\mytest\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\Ben\node\mytest\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\Ben\node\mytest\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Users\Ben\node\mytest\node_modules\tapable\lib\Tapable.js:289:11
    at C:\Users\Ben\node\mytest\node_modules\html-webpack-plugin\index.js:60:9
    at tryCatcher (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
 @ ./node_modules/@ngx-gallery/core/fesm5/ngx-gallery-core.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/@ngx-gallery/core/fesm5/ngx-gallery-core.js
573:49-65 "export 'defineInjectable' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\Ben\node\mytest\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\Ben\node\mytest\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\Ben\node\mytest\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\Ben\node\mytest\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\Ben\node\mytest\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Users\Ben\node\mytest\node_modules\tapable\lib\Tapable.js:289:11
    at C:\Users\Ben\node\mytest\node_modules\html-webpack-plugin\index.js:60:9
    at tryCatcher (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Ben\node\mytest\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
 @ ./node_modules/@ngx-gallery/core/fesm5/ngx-gallery-core.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Compiled with warnings.

```
#### What are the steps to reproduce?

Install it.

#### Which versions are you using for the following packages?

Angular: "@angular/core": "^5.0.0",
Angular CDK: "@angular/cdk": "^6.4.1",
Angular CLI: "@angular/cli": "1.5.5",
Typescript: "typescript": "~2.4.2"
Gallery: "@ngx-gallery/core": "^3.0.2",
    "@ngx-gallery/gallerize": "^3.0.2",
    "@ngx-gallery/lightbox": "^3.0.2",

#### Is there anything else we should know?

I installed it and it doesn't work out of the box.

**Comment by MurhafSousli** [comment]
Angular 5 is not supported with Gallery v3, you should upgrade to Angular 6 or downgrade to Gallery v2.1.1
