### ISSUE TITLE
Breaks my existing test codes

### ISSUE THREAD

**Issue by lobster-man** [MurhafSousli/ngx-gallery#221]
#### What is the expected behavior?
My existing test cases which is not related with gallery to pass.

#### What is the current behavior?
Every tests cases in the component with gallery fails with the message below.

> TypeError: Cannot read property 'reset' of undefined
	    at GalleryComponent.push../node_modules/@ngx-gallery/core/fesm5/ngx-gallery-core.js.GalleryComponent.ngOnDestroy node_modules/@ngx-gallery/core/fesm5/ngx-gallery-core.js:864:1)
	    at callProviderLifecycles node_modules/@angular/core/fesm5/core.js:9573:1)
	    at callElementProvidersLifecycles node_modules/@angular/core/fesm5/core.js:9541:1)
	    at callLifecycleHooksChildrenFirst node_modules/@angular/core/fesm5/core.js:9531:1)
	    at destroyView node_modules/@angular/core/fesm5/core.js:10593:1)
	    at callViewAction node_modules/@angular/core/fesm5/core.js:10719:1)
	    at execComponentViewsAction node_modules/@angular/core/fesm5/core.js:10641:1)
	    at destroyView node_modules/@angular/core/fesm5/core.js:10592:1)
	    at callViewAction node_modules/@angular/core/fesm5/core.js:10719:1)
	    at execComponentViewsAction node_modules/@angular/core/fesm5/core.js:10641:1)

#### What are the steps to reproduce?
Just run any test codes of the component with gallery.

#### What is the use-case or motivation for changing an existing behavior?
Importing this library should not break the test.

#### Which versions are you using for the following packages?

Angular: 6.0.1
Angular CDK: 6.4.5
Angular CLI: 6.0.1
Typescript: 2.7.2
Gallery: 3.2.0

#### Is there anything else we should know?
Actual code runs just like how I expected.
I guess I'm missing something about tests. Can I get some help..?

**Comment by MurhafSousli** [comment]
Currently, this library does not have testing files, I am not sure if this effects your app testing, I don't know!
