### ISSUE TITLE
SSR error

### ISSUE THREAD

**Issue by vpetrusevici** [MurhafSousli/ngx-gallery#532]
Hi! I have an error in Angular Universal when I'm trying to open page with gallery

```
2023-03-28T06:27:52.431090196Z 06:27:52 0|server  | ERROR TypeError: Cannot read properties of undefined (reading 'type')
2023-03-28T06:27:52.432964406Z 06:27:52 0|server  |     at TokenStream.LA (/home/site/wwwroot/server/ru/main.js:3:784952)
2023-03-28T06:27:52.439955943Z 06:27:52 0|server  |     at TokenStream.advance (/home/site/wwwroot/server/ru/main.js:3:783601)
2023-03-28T06:27:52.441232450Z 06:27:52 0|server  |     at Parser._readDeclarations (/home/site/wwwroot/server/ru/main.js:3:817664)
2023-03-28T06:27:52.442853959Z 06:27:52 0|server  |     at Parser.parseStyleAttribute (/home/site/wwwroot/server/ru/main.js:3:819254)
2023-03-28T06:27:52.449141092Z 06:27:52 0|server  |     at parseStyles (/home/site/wwwroot/server/ru/main.js:3:503162)
2023-03-28T06:27:52.459365247Z 06:27:52 0|server  |     at CSSStyleDeclaration.value (/home/site/wwwroot/server/ru/main.js:3:504975)
2023-03-28T06:27:52.460756555Z 06:27:52 0|server  |     at GalleryThumbsComponent.ngOnChanges (/home/site/wwwroot/server/ru/530.js:1:357776)
2023-03-28T06:27:52.462149762Z 06:27:52 0|server  |     at GalleryThumbsComponent.rememberChangeHistoryAndInvokeOnChangesHook (/home/site/wwwroot/server/ru/main.js:3:1896731)
2023-03-28T06:27:52.469147999Z 06:27:52 0|server  |     at callHook (/home/site/wwwroot/server/ru/main.js:3:1911686)
2023-03-28T06:27:52.469851803Z 06:27:52 0|server  |     at callHooks (/home/site/wwwroot/server/ru/main.js:3:1911146)
```

#### What is the expected behavior?
No Error

#### What is the current behavior?
Error :)

#### What are the steps to reproduce?

Just open any page  with gallery from SSR
#### Which versions are you using for the following packages?

Angular: 15.0.4
Angular CDK: 15.0.4
Typescript: 4.9.5
Gallery: 8.0.1

#### Is there anything else we should know?
node version 18

**Comment by vpetrusevici** [comment]
I had also another error before. Related to requestAnimationFrame, but i fixed it with pollyfill
```
global.requestAnimationFrame = function (callback: FrameRequestCallback) {
    let lastTime = 0;
    const currTime = new Date().getTime();
    const timeToCall = Math.max(0, 16 - (currTime - lastTime));
    const id = setTimeout(function () { callback(currTime + timeToCall); },
      timeToCall);
    lastTime = currTime + timeToCall;
    return id as unknown as number;
  };

  global.cancelAnimationFrame = function (id) {
    clearTimeout(id);
  };
```
But would be better to add check in library smth like IsPlatformServer or typeof window !== 'undefined'

**Comment by vpetrusevici** [comment]
Looks like it related to https://github.com/angular/angular/issues/42170

**Comment by vpetrusevici** [comment]
Based on solution from Angular ticket I think we can fix it by adding smth like
`this.slider.style.setProperty('anyProp', 'anyValue');`
after
```
this.slider.style.setProperty('--thumb-height', `${ this.config.thumbHeight }px`);
this.slider.style.setProperty('--thumb-width', `${ this.config.thumbWidth }px`);
 ```

**Comment by vpetrusevici** [comment]
Hi @MurhafSousli,
I created a PR for this. Can you check please?
